BlogSystem/Controllers/BlogController.cs
using BlogSystem.DataAccess.Data;
using BlogSystem.Models.Models;
using Humanizer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.Differencing;
using Microsoft.EntityFrameworkCore;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;
using System.Security.Policy;
using System.Xml;
using System.Diagnostics.Metrics;
using BlogSystem.DataAccess.Repository.IRepository;
using System.Reflection.PortableExecutable;

namespace BlogSystem.Controllers
{
    public class BlogController : Controller
    {
        private readonly IBlogRepository _blogRepository;
        private readonly IUnitOfWork _unitOfWork;
        public BlogController(IUnitOfWork unitOfWork, IBlogRepository blogRepository)
        {
            _unitOfWork = unitOfWork;
            _blogRepository = blogRepository;
        }

        //Response caching reduces the number of requests a client or proxy makes to a web server.
        //Response caching also reduces the amount of work the web server performs to generate a
        //response.Response caching is set in headers.

        [HttpGet]
        [ResponseCache(Duration = 300, Location = ResponseCacheLocation.Client)] 
        public async  Task<IActionResult> Index()
        {
            // Load all blogs
            var blogs = await _unitOfWork.Blog.GetAll();
            return View(blogs);
        }

        public async Task<IActionResult> LazyLoad(int blogId)
        {
            // Lazily loading Comments for a blog post
            var blogs = await _unitOfWork.Blog.GetFirstOrDefault(b => b.Id == blogId);
            if (blogs != null)
            {
                return View(blogs);
            }
            return NotFound();

        }

        public async Task<IActionResult> Edit(int id)
        {
            var blogs = await _unitOfWork.Blog.GetById(id);
            return View(blogs);
        }


        [HttpPost]
        public async Task<IActionResult> Edit(Blog blog)
        {
            // Check if the model state is valid (validations)
            if (!ModelState.IsValid)
            {
                TempData["error"] = "Invalid Blog Details!";
                return View(blog);
            }
            try
            {
                // Update the entity in the context and mark it as modified
                await _blogRepository.UpdateAsync(blog);

                // Save changes to the database
                await _unitOfWork.SaveAsync();

                // Redirect to the index action after successful update
                TempData["success"] = "Blog Updated Successfully.";
                return RedirectToAction("Index");
            }
            catch (DbUpdateConcurrencyException ex)
            {
                // Handle concurrency conflict
                // Get the database values of the conflicting entity
                var entry = ex.Entries.Single().GetDatabaseValues();

                // If the entity was deleted by another user
                if (entry == null)
                {
                    TempData["errro"] = "Unable to save changes. The entity you are trying " +
                        "to update was deleted by another user.";
                }
                else
                {
                    // The entity was modified by another user
                    var databaseValues = (Blog)entry.ToObject();
                    TempData["error"] = "The blog post was modified by another user.";
                    // Update the version (or timestamp) to handle the conflict
                    blog.Version = databaseValues.Version;
                }

                return View(blog);
            }
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Blog blog)
        {
            if (!ModelState.IsValid)
            {
                TempData["error"] = "Invalid Blog Details!";
                return View(blog);
            }

            using var transaction = _unitOfWork.BeginTransactionAsync();
            try
            {
                // Add the entity in the context and mark it as modified
                await _unitOfWork.Blog.Add(blog);
                // Save changes to the database
                await _unitOfWork.SaveAsync();

                // Commit transaction if all commands succeed, transaction will auto-rollback
                // when disposed if either commands fails
                await _unitOfWork.CommitTransactionAsync();

                TempData["success"] = "Blog Created Successfully.";
                // Redirect to the index action after successful update
                return RedirectToAction("Index");

            }
            catch(Exception  ex)
            {
                // Handle exception
                await _unitOfWork.RollbackTransactionAsync();

                TempData["error"] = $"{ex.Message}!";
                return View(blog);
            }
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var product = await _unitOfWork.Blog.GetById(id);
            if (product != null)
            {
                await _unitOfWork.Blog.Delete(product);
                return Json(new { success = true });
            }
            else
            {
                TempData["error"] = "Product not found.";
                return View(product);
            }
        }
    }
}

BlogSystem/Controllers/CommentController.cs
using BlogSystem.DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Mvc;

namespace BlogSystem.Controllers
{
    public class CommentController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CommentController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var comment = await _unitOfWork.Comment.GetAll();
            return View(comment);
        }


    }
}

BlogSystem/Controllers/HomeController.cs
using BlogSystem.Models.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BlogSystem.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BlogSystem/Views/Blog/Create.cshtml
@using BlogSystem.Models.Models;
@model Blog
@{
    ViewData["Title"] = "Create";
}

<form method="post" asp-action="Create" enctype="multipart/form-data">
    <input hidden asp-for="Id" />
    <div class="row col-12">
        <div class="border p-3 mt-4 row">
            <div class="col-12 pb-2">
                <h2 class="text-dark">Create Blog</h2>
            </div>
            <hr />

            <div class="mb-3">
                <label asp-for="Title"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Content"></label>
                <textarea asp-for="Content" class="form-control"></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            
            <div class="col-12">
                <button type="submit" class="btn btn-primary" style="width:150px">Create</button>

                <a asp-controller="Blog" asp-action="Index" class="btn btn-secondary" style="width:150px">Back to List</a>
            </div>
        </div>
    </div>

</form>
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

BlogSystem/Views/Blog/Edit.cshtml
@using BlogSystem.Models.Models;
@model Blog
@{
    ViewData["Title"] = "Edit";
}

<form method="post" asp-controller="Blog" asp-action="Edit" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input hidden asp-for="Id" />
    <input type="hidden" asp-for="Version" />
    <div class="row col-12">
        <div class="border p-3 mt-4 row">
            <div class="col-12 pb-2">
                <h2 class="text-dark">Edit Blog</h2>
            </div>
            <hr />

            <div class="mb-3">
                <label asp-for="Title"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Content"></label>
                <textarea asp-for="Content" class="form-control"></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="col-12">
                <button type="submit" class="btn btn-primary" style="width:150px">Save Changes</button>

                <a asp-controller="Blog" asp-action="Index" class="btn btn-secondary" style="width:150px">Back to List</a>
            </div>
        </div>
    </div>

</form>
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

BlogSystem/Views/Blog/Index.cshtml
@using BlogSystem.Models.Models;
@model List<Blog>
@{
    ViewData["Title"] = "Index";
}

<div class="container">
    <div class="pt-3 pb-4 col-12 row">
        <div class="col-6">
            <h2 class="text-dark"><b>Blog List</b></h2>
        </div>
        <div class="col-6 text-end">
            <div>
                <a asp-controller="Blog" asp-action="Create" class="btn btn-primary">
                    <i class="bi bi-plus-circle"></i> &nbsp; Add Blog
                </a>
            </div>
        </div>
    </div>
    <table id="myTable" class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr class="text-center">
                <th>Title</th>
                <th>Content</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr class="text-center">
                    <td>
                        <a asp-controller="Blog" asp-action="LazyLoad" asp-route-blogId="@obj.Id"
                           class="text-decoration-none">@obj.Title &nbsp;<i class="bi bi-caret-right-fill"></i></a>
                    </td>
                    <td>@obj.Content</td>
                    <td>
                        <div class="w-60 btn-group" role="group">
                            <a asp-controller="Blog" asp-action="Edit" asp-route-id="@obj.Id"
                               class="btn btn-primary mx-2"><i class="bi bi-pencil-square"></i>&nbsp; Edit</a>

                            <a onclick="Delete('/Blog/Delete/@obj.Id')"
                               class="btn btn-danger mx-2"><i class="bi bi-trash"></i> Delete</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <br />
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
    <script>
        function Delete(url) {
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!',
                type: "success"
            }).then((result) => {
                if (result.isConfirmed) {
                    $.ajax({
                        url: url,
                        type: 'DELETE',
                        success: function (data) {
                            if (data.success) {
                                // Blog deleted successfully, show success message
                                Swal.fire("Deleted!", "Blog Deleted Successfully!", "success");
                                setTimeout(function () {
                                    window.location.href = '/Blog/Index';
                                }, 1500);
                            } else {
                                // Blog deletion failed, show error message
                                Swal.fire("Error!", "@TempData["error"]", "error");
                            }
                        }
                    })
                }
            })
        }
    </script>
}

BlogSystem/Views/Blog/LazyLoad.cshtml
@using BlogSystem.Models.Models;
@model Blog
@{
    ViewData["Title"] = "LazyLoad";
}

<h2>@Model.Title</h2>
<p>@Model.Content</p>

<h3>Comments:</h3>
<ul>
    @foreach (var comment in Model.Comments)
    {
        <li>@comment.Content</li>
    }
</ul>

BlogSystem/Views/Comment/Index.cshtml
@using BlogSystem.Models.Models;
@model List<Comment>
@{
    ViewData["Title"] = "Index";
}

<div class="container">
    <div class="pt-3 pb-3 col-12 row">
        <div class="col-6">
            <h2 class="fw-bold">Comment List</h2>
        </div>
    </div>
    <table id="myTable" class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr class="text-center">
                <th>Content</th>
                <th>Blog Title</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr class="text-center">
                    <td>@obj.Content</td>
                    <td>@obj.Blog.Title</td>
                </tr>
            }
        </tbody>
    </table>
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

BlogSystem/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BlogSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlogSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BlogSystem.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BlogSystem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark fw-bold" asp-area="" asp-controller="Blog" asp-action="Index">Blogs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark fw-bold" asp-area="" asp-controller="Comment" asp-action="Index">Comments</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BlogSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BlogSystem/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}